External relations
uoftblueprint/homes-for-heroes pull request #71
Opened 2022-03-20 03:42 UTC by yrao6597

2022-04-05 02:40 UTC, youssefsoli requested changes

2022-04-05 02:40 UTC, youssefsoli commented on Backend/app/controllers/partner.controller.js
> +  },
Use the new error middleware, where `err` is passed to `next()`. See here https://github.com/uoftblueprint/homes-for-heroes/blob/main/Backend/app/controllers/customer.controller.js for reference.

2022-04-05 02:40 UTC, youssefsoli commented on Backend/app/models/partner.model.js
> +};
Try not to use a two-dimensional array for this application, instead use multiple `?`s and a one-dimensional array.

2022-04-05 02:40 UTC, youssefsoli commented on Backend/app/models/partner.model.js
> +        else resolve(rows[0]);
Try returning a Partner object instead, it makes the API usage easier.

2022-04-05 02:40 UTC, youssefsoli commented on Backend/app/models/supporter.model.js
> +const logger = require("../logger");
It seems like double quotes are being prioritized by the editor, can you try installing an eslint plugin to automatically catch styling issues?

2022-04-05 02:40 UTC, youssefsoli commented on Backend/app/models/supporter.model.js
> +      [[this.name, this.date_gifted, this.gift_provided, this.phone]],
Same issue with 2d arrays

2022-04-05 02:40 UTC, youssefsoli commented on Backend/app/models/volunteer.model.js
> +      [[this.name, this.village, this.date_joined, this.role, this.phone]],
ditto

2022-04-07 23:25 UTC, yrao6597 commented
April 7: fixed code based on the requested changes and added controllers to update external relations info

2022-04-07 23:28 UTC, youssefsoli requested changes

2022-04-07 23:28 UTC, youssefsoli commented on Backend/app/controllers/partner.controller.js
> +      res.send(updated_id);
res.json?

2022-04-07 23:28 UTC, youssefsoli commented on Backend/app/controllers/supporter.controller.js
> +      res.send(updated_id);
ditto

2022-04-07 23:28 UTC, youssefsoli commented on Backend/app/controllers/volunteer.controller.js
> +      res.send(updated_id);
ditto

2022-04-07 23:32 UTC, yrao6597 commented on Backend/app/controllers/volunteer.controller.js
> +      res.send(updated_id);
Thanks for the reminder! On it now

2022-04-30 10:00 UTC, youssefsoli requested changes

2022-04-30 10:00 UTC, youssefsoli commented on Backend/app/controllers/partner.controller.js
> +>>>>>>> origin/main
Incomplete merge

2022-04-30 10:00 UTC, youssefsoli commented on Backend/app/controllers/supporter.controller.js
> +>>>>>>> origin/main
ditto

2022-04-30 10:00 UTC, youssefsoli commented on Backend/app/controllers/supporter.controller.js
> +<<<<<<< HEAD
ditto

2022-04-30 10:00 UTC, youssefsoli commented on Backend/app/controllers/volunteer.controller.js
> +<<<<<<< HEAD
ditto

2022-04-30 10:00 UTC, youssefsoli commented on Backend/app/controllers/volunteer.controller.js
> +>>>>>>> origin/main
ditto

2022-05-17 16:09 UTC, closed without merging